# Generated by Django 3.1.3 on 2021-08-04 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_post_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like',
            new_name='user',
        ),
    ]
