# Generated by Django 3.1.3 on 2021-08-04 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='like',
        ),
    ]
